### ISSUE TITLE
Bad Token on BetterGPT

### ISSUE THREAD

**Issue by Alfianurs** [Geniucker/CoGPT#24]
I already follow the instructions to create scheduler task on Windows, also screenshot below is showing that the localhost is running.
I also done running cogpt-get-apptoken.exe
![image](https://github.com/Geniucker/CoGPT/assets/116547863/ccb66e5e-ffcb-47e3-858f-5e378ee173e3)

But when i run on betterGPT it send Badtoken as shown picture below

![image](https://github.com/Geniucker/CoGPT/assets/116547863/aaa2d71b-7c65-41c0-a6dc-92bbc102e25e)

Please guide me to solve the error

**Comment by Geniucker** [comment]
Can you provide the log in `log/cogpt.log`?

**Comment by Geniucker** [comment]
Does your token start with `ghu_`?

**Comment by Alfianurs** [comment]
pardon me, i don't know where to check it?

**Comment by Geniucker** [comment]
After using `cogpt-get-apptoken.exe`, it should give you a token like that
<img width="496" alt="image" src="https://github.com/Geniucker/CoGPT/assets/61449208/9e549be5-4dee-497f-b33c-d4de07be1aa5">

**Comment by Geniucker** [comment]
And you should fill the places where you are aked to fill in OpenAI keys with this token you just got

**Comment by Alfianurs** [comment]
Perfect, it turns out i need to run it with Powershell, then the output is same like you. And now everything work fine. Thank you

**Comment by Geniucker** [comment]
No sweat
