### ISSUE TITLE
[Feature] Network Proxy Setting

### ISSUE THREAD

**Issue by SakuraPuare** [Geniucker/CoGPT#33]
I would like to express my gratitude for your efforts and contributions to this project. I found this project very useful and I use it frequently in my daily work.

But I have found that the program may not work properly in certain network environments, especially in environments that require connectivity through a specific web proxy. This may limit the use of the program in some cases.

I believe this feature would be helpful to many users (myself included), especially those who work in environments that require the use of a web proxy.

**Comment by Geniucker** [comment]
http proxy with `HTTP_PROXY` and `HTTPS_PROXY` env variables set should work.
I'm gonna add support for socks5 proxy soon.

**Comment by Geniucker** [comment]
Could you help test this version: https://github.com/Geniucker/CoGPT/actions/runs/7882895098
Docs have been updated here: https://github.com/Geniucker/CoGPT/tree/proxy?tab=readme-ov-file#proxy

**Comment by SakuraPuare** [comment]
![image](https://github.com/Geniucker/CoGPT/assets/52142762/10e61ada-5e3e-40a4-a3f4-72e1848d4c91)

Maybe I'm messing something up that's causing the function to not work properly, I can make sure my socks proxy is fine (my telegram is working on it)

**Comment by Geniucker** [comment]
说中文吧233
你确定你的7891是socks5端口或者混合端口而不是http端口吗

**Comment by SakuraPuare** [comment]
7891是socks5端口 
![image](https://github.com/Geniucker/CoGPT/assets/52142762/94b7e958-05ea-4aef-9440-a43dfd2f1708)

**Comment by SakuraPuare** [comment]
ok 我自己build了一下 可以了
![image](https://github.com/Geniucker/CoGPT/assets/52142762/d1a04f01-9efd-4d08-aa55-aebccc3e0bc0)

**Comment by SakuraPuare** [comment]
btw 我下载的 action build版本确实没办法连上 自己pull源码编译后可以
arg 是` ./cogpt-api -port 9999 -debug -proxy socks5://localhost:7981` 

![image](https://github.com/Geniucker/CoGPT/assets/52142762/79610b0b-385b-4e70-a051-7786285b715f)
![image](https://github.com/Geniucker/CoGPT/assets/52142762/be726223-ba77-41b6-9ae0-6a3424fd7de8)

两次的log
![image](https://github.com/Geniucker/CoGPT/assets/52142762/8a4fa427-873c-4470-b9e6-9546f81b7cb6)

**Comment by SakuraPuare** [comment]
不管了 可能确实是我的问题

顺带一提 发现个bug： logger的时间不会变
![image](https://github.com/Geniucker/CoGPT/assets/52142762/58c115d6-a04e-4299-a6f4-5f01b5c445b5)

**Comment by Geniucker** [comment]
main分支的有log和socs5相关的依赖的更新，我不知道有没有用

**Comment by Geniucker** [comment]
时间确实不变，太逆天了
