### ISSUE TITLE
API about embedding

### ISSUE THREAD

**Issue by Chrisma-98** [Geniucker/CoGPT#39]
### Description

I noticed that this job is an extension of [copilot-gpt4-service](https://github.com/aaamoon/copilot-gpt4-service)。I'm wondering if CoGPT removed the text embedding api due to API standardization issues. My code returns 404 when POST /v1/embeddings。

BTW, Is it possible to add text embedding func in CoGPT？

**Comment by Geniucker** [comment]
Given that the embeddigns API is not the same as the OpenAI one, I'm not sure if it's necessary to add it.

**Comment by Geniucker** [comment]
I'm gonna add it.

**Comment by Geniucker** [comment]
It will appear in next release
