### ISSUE TITLE
[BUG] <title>反馈

### ISSUE THREAD

**Issue by hA0oooooo** [Geniucker/CoGPT#45]
### Description

![屏幕截图 2024-02-19 003210](https://github.com/Geniucker/CoGPT/assets/140323471/c3e00fa9-2588-43f9-b3c2-5d150bcd7791)
![屏幕截图 2024-02-19 003234](https://github.com/Geniucker/CoGPT/assets/140323471/4366ec09-a4c5-471a-8019-e7778c9213ce)

### Expected Behavior

如图所示。。

### Logs

1

**Comment by hA0oooooo** [comment]
已解决。是没有开通github education。。谢谢

**Comment by Geniucker** [comment]
和#43一样
