### ISSUE TITLE
博客添加例子

### ISSUE THREAD

**Issue by Country-If** [Geniucker/CoGPT#46]
### Description

在作者博客的 [警告](https://blog.geniucker.top/2024/01/26/%E9%80%9A%E8%BF%87-GitHub-Copilot-%E5%85%8D%E8%B4%B9%E4%BD%BF%E7%94%A8-gpt-4/#%E8%AD%A6%E5%91%8A) 部分，能否给出不建议的方式中，`使用 Serverless 服务` 的例子，没接触过这个概念，可以举个例子说明什么是使用了 Serverless 服务吗，感谢

**Comment by Geniucker** [comment]
比如说部署在vercel
