### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wxy000138** [Geniucker/CoGPT#47]
### Description

<img width="239" alt="屏幕截图 2024-02-19 230332" src="https://github.com/Geniucker/CoGPT/assets/135077466/4f240fcb-7de0-4ba1-81d6-0cee97923b54">
<img width="799" alt="屏幕截图 2024-02-19 230344" src="https://github.com/Geniucker/CoGPT/assets/135077466/bfc0845f-70ae-45dc-802c-a749198d96c3">
遇到了如上的报错，请问是什么原因，如何解决，谢谢！

**Comment by Geniucker** [comment]
#43

**Comment by wxy000138** [comment]
OK，谢谢
