### ISSUE TITLE
[BUG] 获取token后在chatgpt next web中设置api后测试报错

### ISSUE THREAD

**Issue by kelo-baby** [Geniucker/CoGPT#48]
### Description

按照教程在Windows端进行服务部署，服务测试进入http://localhost:8080正常，获取token后在chatgpt next web进行api设置，测试对话报错。报错内容如下：
{
  "code": 500,
  "error": "Get \"https://api.github.com/copilot_internal/v2/token\": dial tcp 20.205.243.168:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
}

### Expected Behavior

1

### Screenshots

![error](https://github.com/Geniucker/CoGPT/assets/82890671/7a234549-8a2d-4673-8561-663116499f03)

### Logs

1

### Platform

Windows 10

**Comment by Geniucker** [comment]
看起来是网络问题，时时设置代理

**Comment by kelo-baby** [comment]
> 看起来是网络问题，时时设置代理

试了一下官方gpt是正常可用的，但是在chatgpt next web就不行

**Comment by Geniucker** [comment]
LOG_LEVEL调debug发日志

**Comment by kelo-baby** [comment]
{"level":"info","type":"initCache","time":"2024-02-23T14:46:45+08:00","message":"Initialized cache"}
{"level":"info","type":"config","time":"2024-02-23T14:46:45+08:00","message":"Host: localhost"}
{"level":"info","type":"config","time":"2024-02-23T14:46:45+08:00","message":"Port: 8080"}
{"level":"info","type":"config","time":"2024-02-23T14:46:45+08:00","message":"Cache: true"}
{"level":"info","type":"config","time":"2024-02-23T14:46:45+08:00","message":"CachePath: db/cache.sqlite3"}
{"level":"info","type":"config","time":"2024-02-23T14:46:45+08:00","message":"Debug: false"}
{"level":"info","type":"config","time":"2024-02-23T14:46:45+08:00","message":"LogLevel: debug"}
{"level":"info","type":"config","time":"2024-02-23T14:46:45+08:00","message":"ShareToken: map[]"}
{"level":"info","type":"config","time":"2024-02-23T14:46:45+08:00","message":"Proxy: "}
{"level":"info","type":"startup","time":"2024-02-23T14:46:45+08:00","message":"Start server on localhost:8080"}
{"level":"fatal","type":"startup","time":"2024-02-23T14:46:45+08:00","message":"listen tcp 127.0.0.1:8080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."}
{"level":"error","type":"GetCopilotToken","time":"2024-02-23T14:48:43+08:00","message":"Failed to finish http request, error: Get \"https://api.github.com/copilot_internal/v2/token\": dial tcp 20.205.243.168:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"level":"error","type":"handlerV1ChatCompletions","time":"2024-02-23T14:48:43+08:00","message":"Failed to create http client: Get \"https://api.github.com/copilot_internal/v2/token\": dial tcp 20.205.243.168:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"level":"info","time":"2024-02-23T14:48:43+08:00","message":"Request completed: | 500 |    21.053028s |       127.0.0.1 | POST    /v1/chat/completions"}
{"level":"info","time":"2024-02-23T14:51:12+08:00","message":"Request completed: | 200 |            0s |       127.0.0.1 | OPTIONS /v1/chat/completions"}
{"level":"error","type":"GetCopilotToken","time":"2024-02-23T14:51:33+08:00","message":"Failed to finish http request, error: Get \"https://api.github.com/copilot_internal/v2/token\": dial tcp 20.205.243.168:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"level":"error","type":"handlerV1ChatCompletions","time":"2024-02-23T14:51:33+08:00","message":"Failed to create http client: Get \"https://api.github.com/copilot_internal/v2/token\": dial tcp 20.205.243.168:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"level":"info","time":"2024-02-23T14:51:33+08:00","message":"Request completed: | 500 |   21.0509191s |       127.0.0.1 | POST    /v1/chat/completions"}
{"level":"info","time":"2024-02-23T14:51:33+08:00","message":"Request completed: | 200 |       425.9µs |       127.0.0.1 | OPTIONS /v1/chat/completions"}
{"level":"error","type":"GetCopilotToken","time":"2024-02-23T14:51:54+08:00","message":"Failed to finish http request, error: Get \"https://api.github.com/copilot_internal/v2/token\": dial tcp 20.205.243.168:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"level":"error","type":"handlerV1ChatCompletions","time":"2024-02-23T14:51:54+08:00","message":"Failed to create http client: Get \"https://api.github.com/copilot_internal/v2/token\": dial tcp 20.205.243.168:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"level":"info","time":"2024-02-23T14:51:54+08:00","message":"Request completed: | 500 |   21.0400518s |       127.0.0.1 | POST    /v1/chat/completions"}

**Comment by Geniucker** [comment]
网络问题，试一下设置代理

**Comment by kelo-baby** [comment]
能

**Comment by kelo-baby** [comment]
能请教一下如何设置吗，没太接触过

**Comment by Geniucker** [comment]
文档里写了

**Comment by kelo-baby** [comment]
{"level":"info","type":"updateLogLevel","time":"2024-02-23T21:19:33+08:00","message":"Set log level to info"}
{"level":"info","type":"initCache","time":"2024-02-23T21:19:33+08:00","message":"Initialized cache"}
{"level":"info","type":"config","time":"2024-02-23T21:19:33+08:00","message":"Host: localhost"}
{"level":"info","type":"config","time":"2024-02-23T21:19:33+08:00","message":"Port: 8080"}
{"level":"info","type":"config","time":"2024-02-23T21:19:33+08:00","message":"Cache: true"}
{"level":"info","type":"config","time":"2024-02-23T21:19:33+08:00","message":"CachePath: db/cache.sqlite3"}
{"level":"info","type":"config","time":"2024-02-23T21:19:33+08:00","message":"Debug: false"}
{"level":"info","type":"config","time":"2024-02-23T21:19:33+08:00","message":"LogLevel: info"}
{"level":"info","type":"config","time":"2024-02-23T21:19:33+08:00","message":"ShareToken: map[]"}
{"level":"info","type":"config","time":"2024-02-23T21:19:33+08:00","message":"Proxy: http://localhost:8080"}
{"level":"info","type":"startup","time":"2024-02-23T21:19:33+08:00","message":"Start server on localhost:8080"}
{"level":"fatal","type":"startup","time":"2024-02-23T21:19:33+08:00","message":"listen tcp 127.0.0.1:8080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."}
{"level":"info","time":"2024-02-23T21:19:49+08:00","message":"Request completed: | 200 |            0s |       127.0.0.1 | OPTIONS /v1/chat/completions"}
{"level":"error","type":"GetCopilotToken","time":"2024-02-23T21:20:10+08:00","message":"Failed to finish http request, error: Get \"https://api.github.com/copilot_internal/v2/token\": dial tcp 20.205.243.168:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"level":"error","type":"handlerV1ChatCompletions","time":"2024-02-23T21:20:10+08:00","message":"Failed to create http client: Get \"https://api.github.com/copilot_internal/v2/token\": dial tcp 20.205.243.168:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"level":"info","time":"2024-02-23T21:20:10+08:00","message":"Request completed: | 500 |   21.0658313s |       127.0.0.1 | POST    /v1/chat/completions"}
{"level":"info","time":"2024-02-23T21:20:10+08:00","message":"Request completed: | 200 |            0s |       127.0.0.1 | OPTIONS /v1/chat/completions"}
{"level":"error","type":"GetCopilotToken","time":"2024-02-23T21:20:31+08:00","message":"Failed to finish http request, error: Get \"https://api.github.com/copilot_internal/v2/token\": dial tcp 20.205.243.168:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"level":"error","type":"handlerV1ChatCompletions","time":"2024-02-23T21:20:31+08:00","message":"Failed to create http client: Get \"https://api.github.com/copilot_internal/v2/token\": dial tcp 20.205.243.168:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"level":"info","time":"2024-02-23T21:20:31+08:00","message":"Request completed: | 500 |   21.0742277s |       127.0.0.1 | POST    /v1/chat/completions"}
好像还是不行？😭

**Comment by Geniucker** [comment]
为什么你代理和cogpt的端口都是8080，如果你的代理是8080的话，cogpt的端口要换一个
