### ISSUE TITLE
chatGPT其他应用的配置

### ISSUE THREAD

**Issue by Country-If** [Geniucker/CoGPT#49]
### Description

想问一下，能否接入其他的ChatGPT应用如 [gpt_academic](https://github.com/binary-husky/gpt_academic)，我搭建完 gpt_academic 后，不清楚如何添加第三方的配置，这是官方给出的 [第三方API‐KEY接入指南](https://github.com/binary-husky/gpt_academic/wiki/%E9%A1%B9%E7%9B%AE%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)

**Comment by Geniucker** [comment]
gpt academic可以，只要更改api key格式就行

**Comment by Country-If** [comment]
> gpt academic可以，只要更改api key格式就行

不需要配置API_URL_REDIRECT吗
（另外，开下discussion呗）

**Comment by Geniucker** [comment]
等我一下，我给你个例子

**Comment by Geniucker** [comment]
大概要配置这三个
```
CUSTOM_API_KEY_PATTERN:   '[a-zA-Z0-9]+[_-][a-zA-Z0-9]+'
API_KEY:                  '你的token'
API_URL_REDIRECT:         '{"https://api.openai.com/v1/chat/completions": "http://localhost:8080/v1/chat/completions"}'
```

**Comment by Country-If** [comment]
> 大概要配置这三个
> 
> ```
> CUSTOM_API_KEY_PATTERN:   '[a-zA-Z0-9]+[_-][a-zA-Z0-9]+'
> API_KEY:                  '你的token'
> API_URL_REDIRECT:         '{"https://api.openai.com/v1/chat/completions": "http://localhost:8080/v1/chat/completions"}'
> ```

感谢!
