### ISSUE TITLE
windows下如何改变监听的IP、端口参数？

### ISSUE THREAD

**Issue by lin-xiaosheng** [Geniucker/CoGPT#53]
### Description

使用windows部署后，只能使用localhost:8080访问，不能使用服务器的公网IP访问。查看netstat -an命令后发现只绑定了127.0.0.1：
  TCP    127.0.0.1:8080         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:8080         127.0.0.1:60946        ESTABLISHED
  TCP    127.0.0.1:60946        127.0.0.1:8080         ESTABLISHED
  TCP    127.0.0.1:60947        127.0.0.1:8080         TIME_WAIT
  我该如何做才能在0.0.0.0上监听8080？

**Comment by Geniucker** [comment]
配置文件可以设置监听端口
https://github.com/Geniucker/CoGPT?tab=readme-ov-file#config

**Comment by lin-xiaosheng** [comment]
> 配置文件可以设置监听端口 https://github.com/Geniucker/CoGPT?tab=readme-ov-file#config

在release中下载的[cogpt-windows-amd64.zip]文件里没有.env文件,这是否意味着我手动创建一个即可？需要在哪里引用该文件吗

**Comment by Geniucker** [comment]
和可执行文件同目录即可

**Comment by lin-xiaosheng** [comment]
> 和可执行文件同目录即可

感谢您的耐心回答，我的问题得到解决了
