### ISSUE TITLE
[BUG] <title>Error when acquiring token

### ISSUE THREAD

**Issue by tonyhaohan** [Geniucker/CoGPT#54]
### Description

When I was using cogpt-get-apptoken.exe, it goes black and shuts down itself. It doesn't change when I open it as administrator.
When I open it with powershell (as administrator or not), it says "Request timeout. Please check your network connection and try again."

### Expected Behavior

It should show a code and a website for me to get my token.

### Reproduction Steps

1. open cogpt-get-apptoken as administrator
2. open cogpt-get-apptoken with powershell
3. both of them doesn't work.

### Logs

Request timeout. Please check your network connection and try again.

### Platform

windows 10

**Comment by Geniucker** [comment]
I set a 10s timeout in case the program can't stop due to network problem. But I forgot to pause the program after outputting an error message so it just goes black and shuts itself. I'm gonna fix it soon.

You can try to set proxy env variables like  `https_proxy`
