### ISSUE TITLE
An error is reported in the question

### ISSUE THREAD

**Issue by plateaumylove** [Geniucker/CoGPT#76]
### Description | 描述

![S~3C1_TU SZ5PTY2%I`AQAF](https://github.com/Geniucker/CoGPT/assets/152024591/5865c631-155e-41af-b01e-97d5d01f3846)
按照教程进行无法使用，还是在确保有copilot和github pro的情况下

**Comment by Geniucker** [comment]
https://github.com/Geniucker/CoGPT/discussions/70
