### ISSUE TITLE
[BUG] can't use /v1/chat/completions in zotero-pdf-translate

### ISSUE THREAD

**Issue by Dusker233** [Geniucker/CoGPT#77]
### Description | 描述

在 zotero-pdf-translate 插件中配置了如下 api：
![image](https://github.com/Geniucker/CoGPT/assets/43920034/7b0f7f74-7762-4886-ae70-892d3660b73b)
使用了 share 开头的有效分享密钥，在 zotero 中进行翻译报错：
![image](https://github.com/Geniucker/CoGPT/assets/43920034/91fa1e89-649c-492c-a377-0820299ba867)

模型更改为 `gpt-3.5-turbo` 依然出现此问题。

### Expected Behavior | 预期行为

更换其他 api，如 chatAnywhere 不会出现此问题，可以正常翻译。
![image](https://github.com/Geniucker/CoGPT/assets/43920034/f286a6a4-6fb9-495d-b184-8d1106db3ac5)

使用的接口为 `https://api.chatanywhere.tech/v1/chat/completions`。

### Logs | 日志

 `cogpt.log` 中报错如下：
```text
{"level":"error","type":"handlerV1ChatCompletions","time":"2024-03-04T02:51:13Z","message":"Bad authorization header"}
{"level":"info","time":"2024-03-04T02:51:13Z","message":"Request completed: | 401 |     142.788?s |  ip_address | POST    /v1/chat/completions"}
```

**Comment by Dusker233** [comment]
> cogpt运行的时候最上面会显示配置信息，你看看share token的配置生效了吗

生效的，其他应用（如 chatNextWeb）可以正常使用

**Comment by Geniucker** [comment]
LOG_LEVEL设置成debug，然后翻译一次发一下日志，里面token留一下'share-'或'ghu_'

**Comment by Dusker233** [comment]
调完 `DEBUG=true` 和 `LOG_LEVEL=debug` 后重启容器，可以正常使用了，好怪（

**Comment by Geniucker** [comment]
好怪哈哈哈哈
