### ISSUE TITLE
[BUG] <title>when cogpt-api.exe is closed,it doesn't work

### ISSUE THREAD

**Issue by Achilles0705** [Geniucker/CoGPT#83]
### Description | 描述

只有cogpt-api.exe在打开运行的时候，nextchat才能正常回复，一旦关闭，又会变成failed to fetch

### Expected Behavior | 预期行为

正常运行

### Screenshots | 截图

![屏幕截图 2024-03-09 160416](https://github.com/Geniucker/CoGPT/assets/140709347/88dc2521-cd26-410c-b80e-50ef7e73741c)

### Logs | 日志

![屏幕截图 2024-03-09 160416](https://github.com/Geniucker/CoGPT/assets/140709347/0e13f091-5596-48f9-9d2a-9e59902d69ac)

### Platform | 平台

windows11

**Comment by Geniucker** [comment]
服务端都关了为什么还能正常工作

**Comment by Achilles0705** [comment]
意思是我要一直开着命令窗口才能正常使用吗

**Comment by Geniucker** [comment]
有介绍以服务的形式运行

**Comment by Achilles0705** [comment]
> 有介绍以服务的形式运行

我理解了作者，现在不需要一直在窗口运行，但需要每次开机之后在终端运行
cd C:\CoGPT\    
.\cogpt-api-service.ps1 enable
这两行代码
这样是正确的吗，我是一个初学者，您多多包涵

**Comment by Geniucker** [comment]
理论上来说会开机自动运行

**Comment by Achilles0705** [comment]
> 理论上来说会开机自动运行

不过目前我实践下来确实是需要开机之后在终端输入，才能正常使用，是我哪里配置出问题了吗，谢谢您不厌其烦为我解答

**Comment by Geniucker** [comment]
> > 有介绍以服务的形式运行
> 
> 我理解了作者，现在不需要一直在窗口运行，但需要每次开机之后在终端运行
> cd C:\CoGPT\    
> .\cogpt-api-service.ps1 enable
> 这两行代码
> 这样是正确的吗，我是一个初学者，您多多包涵

执行一次这些，重启之后还是不能用吗

**Comment by XinyongGuo** [comment]
> > 理论上来说会开机自动运行
> 
> 不过目前我实践下来确实是需要开机之后在终端输入，才能正常使用，是我哪里配置出问题了吗，谢谢您不厌其烦为我解答

百度下“如何开机自启动某个程序”

**Comment by Achilles0705** [comment]
> > > 有介绍以服务的形式运行
> > 
> > 
> > 我理解了作者，现在不需要一直在窗口运行，但需要每次开机之后在终端运行
> > cd C:\CoGPT\
> > .\cogpt-api-service.ps1 enable
> > 这两行代码
> > 这样是正确的吗，我是一个初学者，您多多包涵
> 
> 执行一次这些，重启之后还是不能用吗

是这样的，现在我尝试楼上的方法，让其开机自动运行
