### ISSUE TITLE
[FEATURE] It seems that Funcinot calls are not supported when using APIs

### ISSUE THREAD

**Issue by shenmadouyaowen** [Geniucker/CoGPT#88]
### Description | 描述

Does it seem like I don't support funcinot calls when using APIs?
![image](https://github.com/Geniucker/CoGPT/assets/12426724/5b630845-d440-4233-9ae7-50a01e0814b6)

**Comment by Geniucker** [comment]
Community thinks the version of model is gpt-4-0314, which hasn't yet supported function call. So have nothing to do to support it.
